### ISSUE TITLE
Hidden sentences

### ISSUE THREAD

**Issue by leandroneves** [push-flow/bothub-issues#6]
**Description:**  
Scrolling and clicking the button "more", the sentences disappear.

> **Browser:** Chrome
> **OS:** Windows 10  
> **Authenticated**: Yes 
> **URL**: https://bothub.it  

**Steps to reproduce the error:**

1. Access a bot with many sentences
2. Click the more button several times until the end of opening all the sentences.
3. Scroll up and down.

![image](https://user-images.githubusercontent.com/1843614/41124129-5d481dbc-6a77-11e8-835e-10cfa916131d.png)

**Comment by douglasppaz** [comment]
Reported in https://github.com/push-flow/bothub-webapp/issues/100
